src/core/Form/FileManager/DirectoryCreateType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class DirectoryCreateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            TextType::class,
            [
                'label' => 'Name',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new Regex([
                        'pattern' => '#['.preg_quote('\\/?%*:|"<>').'\t\n\r]+#',
                        'match' => false,
                    ]),
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/core/Form/FileManager/DirectoryRenameType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class DirectoryRenameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            TextType::class,
            [
                'label' => 'Name',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new Regex([
                        'pattern' => '#['.preg_quote('\\/?%*:|"<>').'\t\n\r]+#',
                        'match' => false,
                    ]),
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/core/Form/FileManager/FileInformationAttributeType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class FileInformationAttributeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'value',
            TextType::class,
            [
                'label' => 'Value',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }
}

src/core/Form/FileManager/FileInformationType.php
<?php

namespace App\Core\Form\FileManager;

use App\Core\Entity\FileInformation;
use App\Core\Form\Type\CollectionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileInformationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'attributes',
            CollectionType::class,
            [
                'entry_type' => FileInformationAttributeType::class,
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FileInformation::class,
        ]);
    }
}

src/core/Form/FileManager/FilePickerType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class FilePickerType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['pattern'] = null;
        unset($view->vars['attr']['pattern']);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return TextType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'file_picker';
    }
}

src/core/Form/FileManager/FileRenameType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class FileRenameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            TextType::class,
            [
                'label' => 'Name',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new Regex([
                        'pattern' => '#['.preg_quote('\\/?%*:|"<>').'\t\n\r]+#',
                        'match' => false,
                    ]),
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/core/Form/FileManager/FileUploadType.php
<?php

namespace App\Core\Form\FileManager;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\File;

class FileUploadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'files',
            FileType::class,
            [
                'label' => 'Files',
                'required' => false,
                'multiple' => true,
                'attr' => [
                ],
                'constraints' => [
                    new All([
                        new File([
                            'mimeTypes' => $options['mimes'],
                        ]),
                    ]),
                ],
            ]
        );

        $builder->add(
            'directory',
            FileType::class,
            [
                'label' => 'Directory',
                'required' => false,
                'multiple' => true,
                'attr' => [
                    'webkitdirectory' => '',
                    'mozdirectory' => '',
                    'directory' => '',
                ],
                'constraints' => [
                    new All([
                        new File([
                            'mimeTypes' => $options['mimes'],
                        ]),
                    ]),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'mimes' => [],
        ]);
    }
}

src/core/Form/FileUploadHandler.php
<?php

namespace App\Core\Form;

use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * class FileUploadHandler.
 *
 * @author Simon Vieille <simon@deblan.fr>
 */
class FileUploadHandler
{
    protected $filenameGenerator;

    public function setFilenameGenerator(callable $filenameGenerator): self
    {
        $this->filenameGenerator = $filenameGenerator;

        return $this;
    }

    public function handleForm(
        null|array|UploadedFile $uploadedFile,
        string $path,
        ?callable $afterUploadCallback = null,
        ?callable $afterUploadsCallback = null,
        bool $keepOriginalFilename = false
    ): null|array|string
    {
        if (null === $uploadedFile) {
            return null;
        }

        if (is_array($uploadedFile)) {
            $filenames = [];

            foreach ($uploadedFile as $file) {
                $filename = $this->handleForm($file, $path, $afterUploadCallback, null, $keepOriginalFilename);

                if ($filename !== null) {
                    $filenames[] = $filename;
                }
            }

            if (!empty($filenames) && $afterUploadsCallback) {
                $afterUploadsCallback($filenames);
            }

            return $filenames;
        } else {
            $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);

            if ($keepOriginalFilename) {
                $filename = $originalFilename.'.'.$uploadedFile->guessExtension();
            } elseif (!is_callable($this->filenameGenerator)) {
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $filename = date('Ymd-his').$safeFilename.'.'.$uploadedFile->guessExtension();
            } else {
                $filename = call_user_func($this->filenameGenerator, $uploadedFile);
            }

            $uploadedFile->move($path, $filename);

            if ($afterUploadCallback) {
                $afterUploadCallback($filename);
            }

            return $filename;
        }
    }
}

src/core/Form/Filter/RedirectFilterType.php
<?php

namespace App\Core\Form\Filter;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RedirectFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'scheme',
            ChoiceType::class,
            [
                'label' => 'Scheme',
                'required' => false,
                'choices' => [
                    'http(s)://' => 'all',
                    'http://' => 'http',
                    'https://' => 'https',
                ],
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'domain',
            TextType::class,
            [
                'label' => 'Domain',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'domainType',
            ChoiceType::class,
            [
                'label' => 'Type',
                'required' => false,
                'choices' => [
                    'Domain' => 'domain',
                    'Regular expression' => 'regexp',
                ],
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'rule',
            TextType::class,
            [
                'label' => '',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'ruleType',
            ChoiceType::class,
            [
                'label' => 'Type',
                'required' => false,
                'choices' => [
                    'Path' => 'path',
                    'Regular expression' => 'regexp',
                ],
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'location',
            TextType::class,
            [
                'label' => 'Location',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'redirectCode',
            ChoiceType::class,
            [
                'label' => 'Code',
                'required' => false,
                'choices' => [
                    '301 - Moved Permanently' => 301,
                    '307 - Temporary Redirect' => 307,
                ],
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => null,
            'csrf_protection' => false,
        ]);
    }
}

src/core/Form/Site/MenuType.php
<?php

namespace App\Core\Form\Site;

use App\Core\Entity\Site\Menu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class MenuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                    new Length(max: 255),
                ],
            ]
        );

        $builder->add(
            'code',
            TextType::class,
            [
                'label' => 'Code',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                    new Length(max: 255),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Menu::class,
        ]);
    }
}

src/core/Form/Site/NavigationAdditionalDomainType.php
<?php

namespace App\Core\Form\Site;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class NavigationAdditionalDomainType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'domain',
            TextType::class,
            [
                'label' => 'Domain',
                'required' => true,
                'help' => 'Regular expression: do not add the delimiter',
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                    new Length(max: 255),
                ],
            ]
        );

        $builder->add(
            'type',
            ChoiceType::class,
            [
                'label' => 'Type',
                'required' => true,
                'choices' => [
                    'Domain' => 'domain',
                    'Regular expression' => 'regexp',
                ],
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

src/core/Resources/views/form/bootstrap_4_form_theme.html.twig
{% extends 'bootstrap_4_layout.html.twig' %}

{% block builder_widget %}
    {% set row_attr = row_attr|merge({class: 'builder-widget ' ~ (row_attr.class ?? '')}) %}
    {% set value = value is iterable ? value|json_encode : value %}

    {% if value == '' %}
        {% set value = '[]' %}
    {% endif %}

    <div {% for attr, value in row_attr %}{{ attr }}="{{ value }}" {% endfor %}>
        <div class="builder-widget-component" data-value="{{ value }}" data-name="{{ full_name }}" data-id="{{ id }}">
        </div>
    </div>
{% endblock %}

{% block grapesjs_widget %}
    <div class="gjs"></div>
    <div class="d-none">
        <textarea {{ block('widget_attributes') }}>{{ value }}</textarea>
    </div>
{% endblock %}

{% block color_widget %}
    <div class="form-color-container">
        <div class="form-color">
            {%- set type = type|default('color') -%}
            {{ block('form_widget_simple') }}
        </div>
    </div>
{% endblock %}

{% block file_widget -%}
    <div class="row">
        <div class="col-12">
            {% set data = form.vars.data %}

            {% if form.parent.vars.file_type is defined %}
                {% set fileType = form.parent.vars.file_type %}
            {% else %}
                {% set fileType = 'auto' %}
            {% endif %}

            {% if data and form.vars.errors|length == 0 %}
                {% if not data is iterable %}
                    {% set data = [data] %}
                {% endif %}

                <div class="card">
                    {% for item in data %}
                        {% if fileType in ['auto', 'image'] and item.extension in ['jpeg', 'jpg', 'gif', 'png', 'svg', 'webp'] %}
                            <div class="card-img-top bg-tiles text-center">
                                <a href="{{ asset(item.pathname) }}" target="_blank">
                                    <img src="{{ asset(item.pathname) }}" class="img-fluid">
                                </a>
                            </div>
                        {% else %}
                            <div class="card-body">
                                <div class="p-2 text-center">
                                    <a class="btn btn-primary" href="{{ asset(item.pathname) }}" target="_blank">
                                        {{ 'Download'|trans }}
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="card-body">
                        {{- parent() -}}
                    </div>
                </div>
            {% else %}
                {{- parent() -}}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block collection_block_widget %}
    {% set allow_delete = allow_delete|default(false) %}
    {% set allow_add = allow_add|default(false) %}

    <div data-collection="collection-{{ collection_name }}">
        {% for item in form.value %}
            <div data-collection-item="{{ loop.index }}">
                {% for child in item %}
                    {{ form_row(child) }}
                {% endfor %}

                {% if allow_delete %}
                    <div class="text-right">
                        <span data-collection-delete-container class="btn btn-sm btn-danger">
                            <span data-collection-delete="{{ loop.index }}">
                                <span data-collection-delete="{{ loop.index }}" class="fa fa-trash"></span>
                                {{ label_delete|trans }}
                            </span>
                        </span>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if allow_add %}
        <div data-collection-add="collection-{{ collection_name }}" class="collection-add">
            <span class="btn btn-sm btn-primary" data-collection-add="collection-{{ collection_name }}">
                <span data-collection-add="collection-{{ collection_name }}" class="fa fa-plus"></span>
                {{ label_add|trans }}
            </span>
        </div>

        <template type="text/template" id="collection-{{ collection_name }}">
            <div data-collection-item="__name__">
                {{ form_rest(form.value.vars.prototype) }}

                {% if allow_delete %}
                    <div class="text-right">
                        <span data-collection-delete-container class="btn btn-sm btn-danger">
                            {{ label_delete|trans }}
                        </span>
                    </div>
                {% endif %}
            </div>
        </template>
    {% endif %}
{% endblock %}

{% block murph_collection_widget %}
    {% set attrs = attr|merge({class: 'mb-1 ' ~ (attr.class ?? '')}) %}
    {% set allow_delete = allow_delete|default(false) %}
    {% set allow_add = allow_add|default(false) %}

    <div data-collection="collection-{{ collection_name }}" {% for attr, value in row_attr %}{{ attr }}="{{ value }}"{% endfor %}>
        {% for item in form %}
            <div data-collection-item="{{ loop.index }}" {% for attr, value in attrs %}{{ attr }}="{{ value }}"{% endfor %}>
                {% if template_before_item %}
                    {{ include(template_before_item) }}
                {% endif %}

                {% for child in item %}
                    {{ form_row(child) }}
                {% endfor %}

                {% if template_after_item %}
                    {{ include(template_after_item) }}
                {% endif %}

                {% if allow_delete %}
                    <div class="text-right">
                        <span data-collection-delete-container class="btn btn-sm btn-danger">
                            <span data-collection-delete="{{ loop.index }}">
                                <span data-collection-delete="{{ loop.index }}" class="fa fa-trash"></span>
                                {{ label_delete|trans }}
                            </span>
                        </span>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if allow_add %}
        <div data-collection-add="collection-{{ collection_name }}" class="collection-add">
            <span class="btn btn-sm btn-primary" data-collection-add="collection-{{ collection_name }}">
                <span data-collection-add="collection-{{ collection_name }}" class="fa fa-plus"></span>
                {{ label_add|trans }}
            </span>
        </div>

        <template type="text/template" id="collection-{{ collection_name }}">
            <div data-collection-item="__name__" {% for attr, value in attrs %}{{ attr }}="{{ value }}"{% endfor %}>
                {{ form_rest(form.vars.prototype) }}

                {% if allow_delete %}
                    <div class="text-right">
                        <span data-collection-delete-container class="btn btn-sm btn-danger">
                            {{ label_delete|trans }}
                        </span>
                    </div>
                {% endif %}
            </div>
        </template>
    {% endif %}
{% endblock %}

{% block file_picker_widget %}
    <div class="form-filepicker">
        {% set value = form.vars.data %}

        <div class="card">
            {% if value %}
                {% if value.extension is defined and value.extension in ['jpeg', 'jpg', 'gif', 'png', 'svg', 'webp'] %}
                    <div class="card-img-top bg-tiles text-center">
                        <a href="{{ asset(value.pathname) }}" target="_blank">
                            <img src="{{ asset(value.pathname) }}" class="img-fluid">
                        </a>
                    </div>
                {% else %}
                    {% for extension in ['.jpeg', '.jpg', '.gif', '.png', '.svg', '.webp'] %}
                        {% if value ends with extension %}
                            <div class="card-img-top bg-tiles text-center">
                                <a href="{{ asset(value) }}" target="_blank">
                                    <img src="{{ asset(value) }}" class="img-fluid">
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endif %}

            <div class="card-body">
                <div class="d-none">
                    {{- form_widget(form) -}}
                </div>

                <div class="p-2 text-center">
                    <span class="form-filepicker-container">
                        <div class="input-group mb-3">
                            <input class="form-control form-filepicker-picker" data-target="{{ id }}" readonly type="text" value="{{ value }}">
                            <div class="input-group-append form-filepicker-reset" data-target="{{ id }}">
                                <div class="input-group-text btn" data-target="{{ id }}">
                                    <span class="fa fa-backspace" data-target="{{ id }}"></span>
                                </div>
                            </div>
                        </div>

                        <span class="btn btn-sm btn-primary form-filepicker-picker mb-1" data-target="{{ id }}">
                            {{ 'Choose'|trans }}
                        </span>
                    </span>

                    {% if value %}
                        {% if value.pathname is defined %}
                            <a class="btn btn-sm btn-success ml-1 mb-1" href="{{ asset(value.pathname) }}" target="_blank">
                                {{ 'Download'|trans }}
                            </a>
                        {% else %}
                            <a class="btn btn-sm btn-success ml-1 mb-1" href="{{ asset(value) }}" target="_blank">
                                {{ 'Download'|trans }}
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block form_row -%}
    {%- set widget_attr = {} -%}

    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~ "_help"}} -%}
    {%- endif -%}

    {%- if compound is defined and compound -%}
        {%- set element = 'fieldset' -%}
    {% else %}
        {%- set element = 'div' -%}
    {%- endif -%}

    {% if element == 'fieldset' and not ('col-' in form.vars.row_attr.class|default('')) %}
        {% set class = row_attr.class|default('') ~ ' col-md-12 form-group' %}
    {% else %}
        {% set class = row_attr.class|default('') ~ ' form-group' %}
    {% endif %}

    <{{ element }}{% with {attr: row_attr|merge({class: class|trim})} %}{{ block('attributes') }}{% endwith %}>
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_help(form) -}}
    </{{ element|default('div') }}>
{%- endblock form_row %}


{% block form_label -%}
    {% if label is not same as(false) -%}
        {%- if compound is defined and compound -%}
            {%- set element = 'legend' -%}
            {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' col-form-label')|trim}) -%}
        {%- else -%}
            {%- set label_attr = label_attr|merge({for: id}) -%}
        {%- endif -%}
        {% if required -%}
            {% set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {% if label is empty -%}
            {%- if label_format is not empty -%}
                {% set label = label_format|replace({
                    '%name%': name,
                    '%id%': id,
                }) %}
            {%- else -%}
                {% set label = name|humanize %}
            {%- endif -%}
        {%- endif -%}
        <{{ element|default('label') }}{% if label_attr %}{% with { attr: label_attr } %}{{ block('attributes') }}{% endwith %}{% endif %}>
        {%- if translation_domain is same as(false) -%}
            {%- if label_html is same as(false) -%}
                {{- label -}}
            {%- else -%}
                {{- label|raw -}}
            {%- endif -%}
        {%- else -%}
            {%- if label_html is same as(false) -%}
                {{- label|trans(label_translation_parameters, translation_domain) -}}
            {%- else -%}
                {{- label|trans(label_translation_parameters, translation_domain)|raw -}}
            {%- endif -%}
        {%- endif -%}
        </{{ element|default('label') }}>
        {% block form_label_errors %}{{- form_errors(form) -}}{% endblock form_label_errors %}
    {%- else -%}
        {%- if errors|length > 0 -%}
        <div id="{{ id }}_errors" class="mb-2">
            {{- form_errors(form) -}}
        </div>
        {%- endif -%}
    {%- endif -%}
{%- endblock form_label %}